CREATE TABLE cities
(
    id      bigint generated by default as identity,
    name    varchar(255) not null,
    country varchar(255) not null,
    CONSTRAINT cities_pk primary key (id)
);

CREATE TABLE locations
(
    id  bigint generated by default as identity,
    lat float not null,
    lon float not null,
    CONSTRAINT locations_pk primary key (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   bigint generated by default as identity,
    name varchar(50) unique not null,
    CONSTRAINT categories_pk primary key (id)
);

CREATE TABLE attraction
(
    id          bigint generated by default as identity,
    name        varchar(255) not null,
    category_id bigint,
    location_id bigint       not null,
    city_id     bigint       not null,
    CONSTRAINT attraction_pk primary key (id),
    CONSTRAINT attraction_category_fk foreign key (category_id) references categories (id),
    CONSTRAINT attraction_location_fk foreign key (location_id) references locations (id),
    CONSTRAINT attraction_city_fk foreign key (city_id) references cities (id)
)