CREATE TABLE attraction_reviews
(
    id            bigint generated by default as identity,
    comment       text,
    rating        integer,
    author_id     bigint not null,
    attraction_id bigint not null,
    CONSTRAINT attraction_reviews_pk primary key (id),
    CONSTRAINT attraction_reviews_user_fk foreign key (author_id) references users (id) ON DELETE CASCADE,
    CONSTRAINT attraction_reviews_fk foreign key (attraction_id) references attraction (id) ON DELETE CASCADE
);